# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DBDINSTALL += devIpUnidig.dbd

INC += ipUnidig.h

include $(TOP)/config/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
