# Makefile.Vx
TOP = ../../..
include $(TOP)/config/CONFIG_APP

SRCS.cc += ../devIpUnidig.cc ../ipUnidig.cc ../ipUnidigServer.cc

PROD += devIpUnidig.o 
LIBOBJS += ipUnidig.o
LIBOBJS += ipUnidigServer.o
LIBNAME = ipUnidigLib

include $(TOP)/config/RULES.Vx
